---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - tools-tox-linters
        - tools-tox-pep8
        - tools-tox-pylint
    gate:
      jobs:
        - tools-tox-linters
        - tools-tox-pep8
        - tools-tox-pylint
    post:
      jobs:
        - stx-tools-upload-git-mirror

- job:
    name: tools-tox-linters
    parent: openstack-tox-linters
    description: |
      Run linters
    nodeset: debian-bullseye

- job:
    name: tools-tox-pep8
    parent: openstack-tox-pep8
    description: |
      Check conformance with pep8
    nodeset: debian-bullseye

- job:
    name: tools-tox-pylint
    parent: openstack-tox-pylint
    description: |
      Run pylint
    nodeset: debian-bullseye

- job:
    name: stx-tools-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/tools to
      github.com/starlingx/tools
    vars:
      git_mirror_repository: starlingx/tools
    secrets:
      - name: git_mirror_credentials
        secret: stx-tools-github-secret3
        pass-to-parent: true

- secret:
    name: stx-tools-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - VEjvS8EKi9U/gj7Z4OSng7fHdOzTKE3HqehnJy64YzxZF0hBB/pLxdnmD5cxyFOq//PN2
          CYlJTFpUeOvuTNOCs05qQ7Ht6l96n0vTpn/koUR/0fEyrZWoXDwpN2DGhpefd8ioSYvDd
          acwRXVaJx4/r51PWNJmjG5r75XfolM1XKdiF/K4FclNShKWNq0AfuYk90bt7NLP/JWgBf
          M8u74YJZCn1BAgEfqBjyRwZp8qpeLq6H9E+8SUXyilONRo1ijVNgZmEYhSs3JK8GeJ44X
          rkD9+9OF5ZIPQAHRz48zhlMv8Up33jozgvQB14So1AWJAdSZZa3UMFiokGrOmWuRBjyUr
          vHdWznfPRfW0IcnX9P+/uQt6qr5OPjyP2ETELMluKXkATCpZyri0ZYEbZZHuq/ZgwxOH1
          /jobNXkAj3UyycTa9zxtRL0YOMSCycN6LXE8zBf+41TZlK5HS/Ywk1FoZXzJjjbleiApl
          BHo50WHrcIrT24B9uopUI9bD4bi5OiPDyebu87M5/dA9bJzK2Jcx7qX44GfoMkji61rB0
          3kkBRPiPRzO+zzX3o2v/LDe+P30W0LwzESnNBsdkP2Ckx1aDD8dNdnZlQPX7t8L0UZ4LV
          jfPpghjvatmdAIaFKQUGBmLukKvUatV0tqGhcrYPVnaCQnzh0NlfCWaWiXn6rE=
        - Tkd5ox5sX3ZcyG2Ovbj5al3acWyHHUZEWBbnv2fAvsFJYxU25mUzIIuK6MAeQd6cht2g0
          lzK7ywp0OYiG7XJggcpG/6iV9sfdHdx7PZDVvGAzsmKhsOmYRUVC8cQ+5jbt3AKa8d5ma
          p65gCWNfBHXRNx/oEb0E49MUNJfoq7BtYmdlNvpDhZy0eYPvsAq902NAoUa9wRS65FRfG
          czOukdvG7sAIKRRM7kuEN43yfr2iDyR/xif5d812PfiLDo6uok/ZZfqatINc0YLsuWPot
          /pq3R4DAhVraaSeChqks/CFOKlyK2CMRGsgvjF+ZP/c510YArQxzsbzoi5/uB07z2j7Bz
          M1IeCkT1rwuhAi6cSw3Bmy13ocT8+LhBbpaMIx3/BAvt75whCl0h6u4JOKve76IXKEY4W
          jd0ODrsOzqqPWX90o2yG7vyIIIxrdOyFBNxqkdNRrUCovucxWo9TtcTVsH1I/RgoxVG+u
          XGgfUJTbQBjJnEEIKvLChLRHPtkUDwwB8Iknckl4zJg3EJ5OsLnu6LnbB/6yusxDRn5Be
          HuJgeA+GLMXmTJGKlHIeRRCdOqpWhSxuYkNBpsPYhShO2JNCKT/efKWU8L6MFOVStP6DU
          KKuS2GgEr7atIKe+qbCNsjgVsqhn6OlACTXQPktv79/q6bMNN9iSa+4cC0DKF0=
        - GyteOmmBg+NLrmw5A4x+FaqHuHQSpuIqZptwMfi0rKtMQWMHWLxukquyU1mi7lIcuEsA0
          oJ4AxDKn8d4imd4jp1MMY6jLhoHlayvPdWpxMpmutR8tI0k1K7j6KJ+kDgAM8fOstrcvz
          dIXcoaRmQX3YZdaYLOD/moQtjzPzHy0me5Mxl2rKgOg3XQWda9+fltePHl+gGxiYDff6k
          occIopz39QgbfQqvSEzNL6MF/Ce5nUdS+Qv4dfjkDsAC0utj28oW54+jNkCe69abBYhwT
          oVvZl6gSLtjEI1UFQPsdcnz2Bdq7eKGnnUcxpflVSRwOR5/d9ofvZexC1oyqaCOZ9I84I
          E7R/2VZVE34tRPFbdrNTm7rDm5nwYU0HQAPm72NeeI2PwlBihX3NlaNBZc79I6hrAPmpy
          yenXv7Zq58x8oYMktsldfQZxqNBvtWkvU44qkqZTl5sj91a2kQ0EVB4JZMFUIg/tSVaBq
          FREk5COUrayXkbbkNU32DV9BKtHIeWfMbWx4ppIOe4HYrSeNhRRBh2VwoKZtdPbO9IsOx
          xp0NU+cUxrH359no/8TLLOKHKWZdrDLsknJNZPoDLC3oU2cLdLzt0ys8zDZuyP+DAbSh+
          NkF7PH5JlB30596pV1DmnRYYwTUknTVKjqG/D/vIltE8Cy6RVwxDrjnPmlqfA0=
        - tHejEgotB28IMTJGjbdZZUEYYWaHR4yJrCyRBa27SJ/eNozLQqyZeEdcYXNKVrhxodpHz
          qj2HczxlVNEH1BMM1lgkPwr3pGqLz+JDKDgqs7tBCBabYK9D2oxSrqvesgJL2+FHMeVad
          522tc4Q4ZfRL8p2rZOpTm+0ASrpH3nzHgmjAx4Cr9WQqMghnB62Tb5JkoZFhOYRa0PQCg
          xYYGaTVxg3neDCfggRO8QDlwM/qSzBzRlkfEbf4I3x/G7/Grp9JgIqYMrXBnxbcnp15Vb
          rNaY/ijRPWUR4/6aqPtOs0AFU0j9Jw1GRdgQ9vsLdqCl8+v1xXP268XKwlOcRpGd9h63Z
          zTd0UNJRq71EdLbjoX/dWtVZnkBnaC5T6AhV/zUgz+09c9mhlEBTDyfBNPL9e4GtLEXSO
          nC2mV9hKiTh0LYkemDcxmph+KvXXq6o7kNk7eyRYvX42KpzWxc63IRcD7SGz8CAIsxcUv
          4mJ5yf6f9RA2526S70cEZRcCLdVDmEMiNwwuoWEZy0w+fmYFUzc0+Awg4w2kABV/sKS9e
          J0rMnmtVCfIdalS92CkhfplnT3fc1YJP1rDB93POneeJqT0TNIX+llkrTxeSY1Lk0Oe1/
          Hdv05Q0DlVkua7lz1L2j31kjSPxLB+dWLMkLC90qutQHZePNRTJYEx1nA2eQWY=
        - tsqEocTZY+LxNcxkTFJOwg4PiDwgTziURAvNev17iWZWNbqROA/fhZTzwuji/3++lvfCP
          NidWcc2ufSw2GVTO5BsnX7h3UhVLVrS/JLla2LDl+WNPoD9qS801w/qiTbSTzLCb9bo+H
          oo2KTHgz9/5eVtxWJuS4hmV5eNuRZbr1pcnnrIV4pKon1VkyQAJPqYGOVfzTQRIuTWnup
          NJwcRMCVkv+zdppWtaKmtlyHaLs2xrSC8hiOtlFBXDfOKg/PpV47usGPYWEEe727BTrjG
          brUnp5BCup6TkjKstjt87OJg0kaRXQyWPUJstrzALBJwxb/pLF3hA9VYKBWCS/j7Q9Vg4
          AyIrr2k8DN5RhDFbJPckL8fq1ktQlDE/k6fBrpEFtWsRWktvREdWJMeuWUtVtCaquSVHy
          zBrCl7fdYQusvR5vnuMMexao6/djwDijy8M/4uwGMJWpqW3i5pAyZNvvTwdcNk09XjtQm
          sE+VP0FVSNODqhlcazLFANTT6EJkItqChF32yx+Clxd84g4GVZ3ymFDfxqlX0+cyST2rK
          TtOdCvDxGUP0Jukip2e2W5i4y4chzgYF3PRb2KGiv2ewO3vDIwxDnhPxW/mrMxjrqnCSD
          nCJbm86vfE04vWUlp/+jhVkXtsDgzdfG3LlEDz3HSEQkJCCGV2d+IxzVt2lWek=
        - EzuELTu9TCSDiM9PkXHzZKDRn1uIi8SQDvkL1Muc8iXkxNIfj7/2X5t2w6Y3ZRYiVDCJL
          KI5qAvjD1v7vWOZ+iyXTnAjL+r9XzP/3pHSwSW1E6OGuXg8qT9HXrGxJCCOo+eFo6mWw3
          PPjGEmsjgKstzWuO+LZrG83m58I9WHUw8kN8UqCC77/+qxcNaTpUHCDfRy8eBcGE7nGRF
          qbC3u8V2GsHkglUO8R/2cwJVsSJz9T4+MYOpZ7IV5l5kMjgABMFcXlHafoT5JRHDQ04m3
          0UTV9RzBeF/UAypb1wZSi5e1AODvrpibtjgTdiD4wqMbLQitp6D9oCUVPJOH7YfpLiqd9
          pvg9+rj8gf8QTq1IIFd7+W/rkLw1Ex62GTAWUKaxfCqkSkNWPcw1T8N1tf+qzWWXkwVad
          PSpNMfjP/bL4XW0BI+o+aW6BvQCa9Zp89PnLcEBQAH3zSgJRv9E6dUyiVZbWqeM0rP8v7
          4LJBX1LSGmIayP+BJhalSvYS6H6bBJ3qVniqgiYUheFNIUtXa0uT5WE7/GSZTYKtusreI
          IAhULyb6yqBq1QkBmtHsfYxqvIRq7JvdxH7dI82zsaSROpdnPEhY2jw0wPCbcgPbDn/SP
          C6ptKQ+ujDFFOeM5vqxXNRgC4hG8cveUk3Z0JhbnwtSwXJHLH2FZkXEOEiQhDQ=
        - fRRU19HRoUTKqxSzhDLpSG9YKc3JARaqaI+UZbP7+bDmfnjHTa+YihhEz8EBvqjRAkKTV
          ICPTSA2ui0T4O/uq1PKpId8f86JFVtZwXvX+qm4tOE3f5ffFe4ln5vl/kxJluo8Raqri4
          u+3gk8Cv7whHchrhuJwabu7dSmd4+NQgCs5XXV082ygyHIds3Zjdhw/u+vOO0srPrro0d
          YNiTD4Yn0joCF+EQ5+6sTnpyqoh+Mk/x18MaiEpjfYgDac4A2+dAI9cwi4cA2wSWQjDGB
          joYQEzvoHi5IsA6+4jfycche/g8LS2sLHTKfavB7Okr+9hXs/XNSIJqaF+OkkQsDRFAyH
          2Uk+76ZrIAEcJ0/OHuDKxQHqhfxe4vIH2tsO6lIvRFx7jEAZZR4zS/6WyrcAnl8D4Rock
          RkPxC//wiVsbTfb1vmt/NSAOiSssu+eNeMiHjnqmqlfE7E14+P1/9Dpv2hgwoi6mLYYIb
          4dXb2rw/b0PgWnVD2XZFZ88duQBeEXCnBoRG/OpDcO45BHMTAur93U6dBzkYQUPpVvzZD
          FN3zS0fdOnrN07GxxkZQVxFypVO/oxlqmm4V9eSoMRXIALa6OdN/i1uMlx+sNPgUMEFm6
          w8v2be/Itj7aBtEkDKWaK9+S6NWWJhjhgn9TjUBcWPAAgGNAg+jklPusX3Tl64=
